const actBooking = {
    GET_SEAT_COMBO_PRICE_DATA: "GET_SEAT_COMBO_PRICE_DATA",
    SET_SEAT_COMBO_PRICE_DATA: "SET_SEAT_COMBO_PRICE_DATA",
    GET_UNAVAILABLE_SEAT: "GET_UNAVAILABLE_SEAT",
    SET_UNAVAILABLE_SEAT: "SET_UNAVAILABLE_SEAT",
}

export default actBooking;