const actLogin = {
    SET_LOGIN_FORM_SHOW_STATUS: "SET_LOGIN_FORM_SHOW_STATUS",
    GET_LOGIN_DATA: "GET_LOGIN_DATA",
    SET_LOGIN_DATA: "SET_LOGIN_DATA",
    SET_LOGIN_STATUS: "SET_LOGIN_STATUS",
    SET_SIGNUP_STATUS: "SET_SIGNUP_STATUS",
    CREATE_ACCOUNT: "CREATE_ACCOUNT",
    SET_NAME_PUT_STATUS: "SET_NAME_PUT_STATUS",
    SET_PASWORD_PUT_STATUS: "SET_PASWORD_PUT_STATUS",
    DELETE_ACOUNT: "DELETE_ACOUNT",
}

export default actLogin;