const actMovie = {
    GET_ALL_MOVIE: "GET_ALL_MOVIE",
    SET_ALL_MOVIE: "SET_ALL_MOVIE",
    GET_MOVIE_DETAIL: "GET_MOVIE_DETAIL",
    SET_MOVIE_DETAIL: "SET_MOVIE_DETAIL",
    GET_MOVIE_DATA: "GET_MOVIE_DATA",
    SET_MOVIE_DATA: "SET_MOVIE_DATA",
    GET_MOVIE_BY_CINEMA_CODE: "GET_MOVIE_BY_CINEMA_CODE",
    SET_MOVIE_BY_CINEMA_CODE: "SET_MOVIE_BY_CINEMA_CODE",
}

export default actMovie;