const actOrder = {
    SET_SEAT_COMBO_COST_ORDER: "SET_SEAT_COMBO_COST_ORDER",
    SET_MOVIE_ORDER: "SET_MOVIE_ORDER",
    SET_CINEMA_ORDER: "SET_CINEMA_ORDER",
    SET_SESSION_ORDER: "SET_SESSION_ORDER",
    POST_TICKET: "POST_TICKET",
    SET_PAYMENT_STATUS: "SET_PAYMENT_STATUS",
}

export default actOrder;